name: elo
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.*
  - _openmp_mutex=5.*
  - asciitree=0.*
  - asttokens=2.*
  - autopep8=1.*
  - backcall=0.*
  - beautifulsoup4=4.*
  - blas=1.*
  - bokeh=2.*
  - bottleneck=1.*
  - brotli=1.*
  - brotlipy=0.*
  - bzip2=1.*
  - ca-certificates=2022.*
  - certifi=2022.*
  - cffi=1.*
  - charset-normalizer=2.*
  - click=8.*
  - cloudpickle=2.*
  - cryptography=37.*
  - cudatoolkit=11.*
  - cycler=0.*
  - cytoolz=0.*
  - dask=2022.*
  - dask-core=2022.*
  - dbus=1.*
  - decorator=5.*
  - distributed=2022.*
  - executing=0.*
  - expat=2.*
  - fasteners=0.*
  - ffmpeg=4.*
  - fontconfig=2.*
  - fonttools=4.*
  - freetype=2.*
  - fsspec=2022.*
  - giflib=5.*
  - glib=2.*
  - gmp=6.*
  - gnutls=3.*
  - gst-plugins-base=1.*
  - gstreamer=1.*
  - heapdict=1.*
  - icu=58.*
  - idna=3.*
  - intel-openmp=2021.*
  - ipython=8.*
  - jedi=0.*
  - jinja2=3.*
  - joblib=1.*
  - jpeg=9e
  - kiwisolver=1.*
  - lame=3.*
  - lcms2=2.*
  - ld_impl_linux-64=2.*
  - libffi=3.*
  - libgcc-ng=11.*
  - libgfortran-ng=7.*
  - libgfortran4=7.*
  - libgomp=11.*
  - libidn2=2.*
  - libllvm11=11.*
  - libopus=1.*
  - libpng=1.*
  - libstdcxx-ng=11.*
  - libtasn1=4.*
  - libtiff=4.*
  - libunistring=0.*
  - libuuid=1.*
  - libvpx=1.*
  - libwebp=1.*
  - libwebp-base=1.*
  - libxcb=1.*
  - libxml2=2.*
  - llvmlite=0.*
  - locket=1.*
  - lz4=3.*
  - lz4-c=1.*
  - markupsafe=2.*
  - matplotlib=3.*
  - matplotlib-base=3.*
  - matplotlib-inline=0.*
  - mkl=2021.*
  - mkl-service=2.*
  - mkl_fft=1.*
  - mkl_random=1.*
  - msgpack-python=1.*
  - munkres=1.*
  - ncurses=6.*
  - nettle=3.*
  - numba=0.*
  - numcodecs=0.*
  - numexpr=2.*
  - numpy=1.*
  - numpy-base=1.*
  - openh264=2.*
  - openssl=1.*
  - packaging=21.*
  - pandas=1.*
  - parso=0.*
  - partd=1.*
  - pcre=8.*
  - pexpect=4.*
  - pickleshare=0.*
  - pillow=9.*
  - pip=22.*
  - prompt-toolkit=3.*
  - psutil=5.*
  - ptyprocess=0.*
  - pure_eval=0.*
  - pycodestyle=2.*
  - pycparser=2.*
  - pygments=2.*
  - pyopenssl=22.*
  - pyparsing=3.*
  - pyqt=5.*
  - pysocks=1.*
  - python=3.*
  - python-dateutil=2.*
  - python_abi=3.*
  - pytorch=1.*
  - pytorch-mutex=1.*
  - pytz=2022.*
  - pyyaml=6.*
  - qt=5.*
  - readline=8.*
  - requests=2.*
  - scikit-learn=1.*
  - scipy=1.*
  - selenium=3.*
  - setuptools=61.*
  - sip=4.*
  - six=1.*
  - sortedcontainers=2.*
  - soupsieve=2.*
  - sqlite=3.*
  - stack_data=0.*
  - tbb=2021.*
  - tblib=1.*
  - threadpoolctl=2.*
  - tk=8.*
  - toml=0.*
  - toolz=0.*
  - torchaudio=0.*
  - torchvision=0.*
  - tornado=6.*
  - tqdm=4.*
  - traitlets=5.*
  - typing_extensions=4.*
  - tzdata=2022a
  - urllib3=1.*
  - wcwidth=0.*
  - wheel=0.*
  - x264=1!157.*
  - xz=5.*
  - yaml=0.*
  - zarr=2.*
  - zict=2.*
  - zlib=1.*
  - zstd=1.*
